### ISSUE TITLE
Please add more details to README.md / Por favor agrega mas detalles a README.md

### ISSUE THREAD

**Issue by t33st33r** [StarDustCFW/LinkUser#1]
Your homebrew takes files from **sd:/switch/LinkUser/su** to restore a linked NNID account but I don't know how to back up my NNID. What files do I have to take? Where are those files?
Thanks in advance. Have a wonderful holiday season.

Tu homebrew toma archivos de **sd:/switch/LinkUser/su** para restaurar una cuenta NNID vinculada pero no se como hacer el backup de mi NNID. ¿Que archivos debo tomar y de donde?
Gracias de antemano y felices fiestas.

**Comment by Kronos2308** [comment]
Sólo se hace un backup cuando se linka un usuario
A backup is only made when a user is linked
In sd/switch/linkuser/sume

For restore you must put the 'su' folder in 
sd/switch/linkuser/ su

Is all explain in the app 

The kuhaku account is stored in romfs

**Comment by t33st33r** [comment]
"Solo se hace backup cuando se linka un usuario"
Esto lo interpreto como que este homebrew revisa si hay algun NNID linkado en el momento de abrirse y, en caso de encontrarlos, hace backups de ellos.

¿Es esto correcto?

**Comment by Kronos2308** [comment]
Ojalá funcionara tan fino 
En realidad solo revisa si hay un backup hecho a la hora de linkar 
Si no hay backup lo hace
O sea ya que linkar un usuario sobrescribe todos los anteriores
Se hace un backup de como lo tenias hasta ese momento para evitar accidentes

**Comment by t33st33r** [comment]
OK ya me quedo claro con esto ultimo.
Gracias por la aclaracion.

**Comment by t33st33r** [comment]
Suerte que no cerraste este hilo... te queria comentar algo que no era realmente un "issue" (por tanto no corresponderia abrir uno nuevo).
El tema es que para el tema de la cuenta NNID (vinculado+transferencia) es necesario:
1ª · Estar en OFW para vincular la cuenta desde las propias opciones de la consola (esto por seguridad) y debe ser la ultima version (lo cual nos obligaria a quemar eFuses) por exigencias de la consola.
2º · Correr CFW en sysNAND (lo cual a muchos no les gusta y obligaria a revertir el proceso con Haku33 una vez terminado el ultimo punto).
3º · Ya con CFW correr LinkUser para hacer el backup del perfil que tiene ya la cuenta vinculada.
4ª · Correr LinkUser en la emuNAND para restaurar el perfil.
5º (Esto lo querran muchos) · Eliminar el hack de la sysNAND mediante Haku33

En resumen... una movida tremenda. Por ello he creado un hilo en GBAtemp con la idea de que alguien cree una aplicacion de escritorio que permita iniciar sesion en la cuenta NNID y a partir de la sesion cree el backup de un nuevo perfil limpio pero ya con la cuenta NNID vinculada. Y con la idea de hacerte llegar el enlace al hilo por si te interesara el proyecto para trabajar en el... ya sea en solitario o en colaboracion con algun desarrollador de GBAtemp o GitHub.

Un saludo.

En link al hilo: http://gbatemp.net/threads/_.555481/

**Comment by Kronos2308** [comment]
Te deje una respuesta en el hilo
